### ISSUE TITLE
Tar extract strip: 1 is buggy

### ISSUE THREAD

**Issue by aminya** [iwatakeshi/gitly#10]
Tar `strip: 1` results in some of the files being missing when the file is extracted. Could you find a better way to move the files to the destination directory? 

https://github.com/iwatakeshi/gitly/blob/b68b961b58333824dd014c7c21b0d53df338c473/src/utils/extract.ts#L31

**Comment by iwatakeshi** [comment]
@aminya Hmm, I'll have to think about how to go about that. Do you think using `zip` instead of tar be a better approach?

**Comment by iwatakeshi** [comment]
I believe this has been addressed in npm/node-tar#282. Closing this issue.
