### ISSUE TITLE
Would you consider supporting gitee

### ISSUE THREAD

**Issue by wegi8** [iwatakeshi/gitly#21]

**Comment by iwatakeshi** [comment]
@wegi8 Hi, I've never used gitee. If you know the url or path to download the `.tar.gz` file, it should be easy to add that url [to this file](https://github.com/iwatakeshi/gitly/blob/b74b0ee441e3d2327d1ff2fafd1c8588e6495f74/src/utils/tar.ts#L8).

Technically, there is a[ `filter` option](https://github.com/iwatakeshi/gitly/blob/b74b0ee441e3d2327d1ff2fafd1c8588e6495f74/src/utils/tar.ts#L12) to override the `getFile` function.

Feel free, to contribute if you can :).

**Comment by wegi8** [comment]
OK, I will try to get the download address of gitee. If successful, I will add it to the `switch`.

**Comment by wegi8** [comment]
Unfortunately, This doesn't work, Gitee needs to be logged in to download. @iwatakeshi

**Comment by iwatakeshi** [comment]
@wegi8 That is unfortunate. If gitee does support public downloads in the future, you are welcomed to create a pull request :).

**Comment by wegi8** [comment]
@iwatakeshi Yes, I will, if it's open for download. At present, I am working on a small tool for downloading templates for my own use. I need to download projects from GitHub and other platforms. Since I am in China, I need to support gitee for developers without agent tools
