### ISSUE TITLE
How to download and extract a git repository from bitbucket, gitLab or custom gitlab?

### ISSUE THREAD

**Issue by imjeen** [iwatakeshi/gitly#9]
- gitly: `2.0.3`
- Typescript: `4.2.4`
- node: `14.4.0`

Try to download a gitlab repository and respond an array with empty string. And then nothing to download.

```ts
const url = `<url for bitbucket, gitLab or custom gitlab>`;
const destination =  path.resolve(process.cwd(), `./test`);
const res = await gilly(url, destination, {}); 
// response data is empty: ['', '']
```
However, I found the [gittar](https://github.com/lukeed/gittar#repo) can download other repo.

**Comment by imjeen** [comment]
By the way. Writing code with typescript, I meet some different ways.

-  `npm i gittly`: and must to do: `npm i -D @types/tar`.
- `await gilly(url, destination); `:  the third params should be optional.

**Comment by iwatakeshi** [comment]
Hi @imjeen , thanks for the report. I just tried gittar, but I think gittar is [having issues](https://runkit.com/iwatakeshi/6086fc308f7fbd001aefd6c9) downloading the tar file from gitlab as well. I wonder if gitlab changed the url or if this is temporary.

I'll be working on a new version and it will be available on a new branch later on so if you're interested in looking it, I can ping you.

**Comment by iwatakeshi** [comment]
@imjeen You can check out the `next` branch for the latest version. Note that the issue is still there and [can be seen in the CI](https://github.com/iwatakeshi/gitly/runs/2442060709?check_suite_focus=true#step:6:11).

**Comment by imjeen** [comment]
The [test#78](https://github.com/iwatakeshi/gitly/blob/4779e6e6c15918d777f2deada4cb61d323216e8b/src/utils/__test__/fetch.spec.ts#L78) with gitlab cannot be passed in my Mac. 😰

**Comment by iwatakeshi** [comment]
@imjeen Yeah, I'll look into this this weekend, but if you want to look into it as well, I'd appreciate it :).
